# Generated by Django 2.2.5 on 2019-09-18 06:44

import django.contrib.postgres.fields.citext
from django.db import migrations, models
import rbq_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('rbq_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', rbq_backend.models.AccountManager()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='acct',
            field=django.contrib.postgres.fields.citext.CITextField(unique=True, verbose_name='full username'),
        ),
    ]
