# Generated by Django 2.2.5 on 2019-09-18 06:46

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbq_backend', '0002_auto_20190918_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=django.contrib.postgres.fields.citext.CITextField(null=True, unique=True),
        ),
    ]
