# Generated by Django 2.2.5 on 2019-09-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbq_backend', '0004_auto_20190918_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_moderator',
            new_name='is_staff',
        ),
    ]
