# Generated by Django 2.2.5 on 2019-09-18 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbq_backend', '0006_auto_20190918_0654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asactivity',
            options={'verbose_name_plural': 'ASActivities'},
        ),
        migrations.AlterModelOptions(
            name='asobject',
            options={'verbose_name_plural': 'ASObjects'},
        ),
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_type', models.CharField(choices=[('owner', 'Owns'), ('moderator', 'Moderates'), ('poster', 'Posts to')], max_length=50)),
                ('bourgeoisie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exploits', to=settings.AUTH_USER_MODEL)),
                ('proletariat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exploited_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
