# Generated by Django 2.2.5 on 2019-09-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbq_backend', '0008_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='admin_type',
            field=models.CharField(choices=[('owner', 'Owns'), ('moderator', 'Moderates'), ('poster', 'Able to post on')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='asactivity',
            table='as_activities',
        ),
        migrations.AlterModelTable(
            name='asobject',
            table='as_objects',
        ),
        migrations.RunSQL(
            "CREATE UNIQUE INDEX as_objects_unique_ap_id_idx ON as_objects ( (data->>'id') ) ;"
        ),
        migrations.RunSQL(
            "CREATE UNIQUE INDEX as_activities_unique_ap_id_idx ON as_activities ( (data->>'id') ) ;"
        ),
    ]
