# Generated by Django 2.2.5 on 2019-09-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbq_backend', '0010_auto_20190918_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='inbox',
            new_name='inbox_uri',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='outbox',
            new_name='outbox_uri',
        ),
        migrations.AddField(
            model_name='account',
            name='followers_uri',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='following_uri',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='private_key',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='public_key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
