# Generated by Django 2.2.5 on 2019-09-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbq_backend', '0011_auto_20190918_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='followers_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='following_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='posts_count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
