# Generated by Django 2.2.5 on 2019-09-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbq_backend', '0012_auto_20190918_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('Person', 'Person'), ('Service', 'Bot'), ('Group', 'Subforum')], default='Person', max_length=50),
        ),
        migrations.AlterModelTable(
            name='asactivity',
            table=None,
        ),
        migrations.AlterModelTable(
            name='asobject',
            table=None,
        ),
    ]
