# Generated by Django 2.2.5 on 2019-09-27 04:24

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbq_backend', '0016_auto_20190919_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=django.contrib.postgres.fields.citext.CITextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='asactivity',
            name='domain',
            field=django.contrib.postgres.fields.citext.CITextField(),
        ),
        migrations.AlterField(
            model_name='asactivity',
            name='recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
    ]
